self: super:

with self.pkgs; {
  # wait for tailscale to bind
  tailscaleWaitOnline = lib.mkBefore [
    "${pkgs.bash}/bin/bash -c 'until ${pkgs.iproute2}/bin/ip addr show dev tailscale0 | ${pkgs.gnugrep}/bin/grep -q -E \"inet 100(\.[0-9]{1,3}){3}\"; do sleep 5; done'"
  ];
  tailscaleAfter = lib.mkAfter [
    "tailscaled.service"
  ];
  tailscaleRequires = lib.mkAfter [
    "tailscaled.service"
  ];
  tailscaleWantedBy = lib.mkAfter [
    "network-online.target"
  ];
  systemd-services = {
    services = {
      harmonia.serviceConfig.ExecStartPre = pkgs.tailscaleWaitOnline;
      harmonia.after = pkgs.tailscaleAfter;
      harmonia.wantedBy = pkgs.tailscaleWantedBy;
      harmonia.requires = pkgs.tailscaleRequires;
      # The hardened service's RestrictAddressFamilies is breaking the tailscale lookup (via AF_NETLINK)
      # https://github.com/NixOS/nixpkgs/blob/nixos-25.05/nixos/modules/services/networking/harmonia.nix#L112
      harmonia.serviceConfig.RestrictAddressFamilies = lib.mkForce "AF_UNIX AF_INET AF_INET6 AF_NETLINK";

      syncthing.serviceConfig.ExecStartPre = self.pkgs.tailscaleWaitOnline;
      syncthing.after = pkgs.tailscaleAfter;
      syncthing.wantedBy = pkgs.tailscaleWantedBy;
      syncthing.requires = pkgs.tailscaleRequires;

      wireproxy =
        let
          # wg profiles generated by:
          # > mozwire relay save -o ./mozillavpn -n 0
          run_wireproxy = pkgs.writeShellScript "run_wireproxy" ''
            ${self.pkgs.wireproxy}/bin/wireproxy --silent --config <(cat <<-EOF
            WGConfig = /home/james/notes/mozillavpn/nl-ams-wg-001.conf
            [Socks5]
            BindAddress = 127.0.0.1:1080
            EOF
            )
          '';
        in
        {
          description = "Wireproxy SOCKS server service";
          after = [ "network-online.target" ];
          wantedBy = [ "network-online.target" ];
          serviceConfig.ExecStart = run_wireproxy;
        };
    };
    timers = {
    };
    user = {
    };
  };
}
